---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install
  - mkdir -p tmp && cd tmp
  - wget http://www.webdav.org/neon/litmus/litmus-0.13.tar.gz
  - tar -zxf litmus-0.13.tar.gz
  - cd litmus-0.13
  - sed -i -e "s/T\(propfind_invalid2\),//g" src/props.c
  - ./configure && make
  - cd ../..

script:
  - npm test
  - npm run test-server
  - PORT=6849 node app.js &
  - cd tmp/litmus-0.13 && make OPTS="-k" URL=http://localhost:6849/remote.php/webdav check
